apiVersion: v1
kind: Service
metadata:
  name: ccwardrobe-service
  namespace: ccwardrobe
spec:
  selector:
    app: ccwardrobe
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30000
